### PR TITLE
Test against Keycloak 11.0.2

### PR DESCRIPTION
**Pull request by treydock**

### CODE REVIEW

**Comment by treydock** [comment]
Blocked by bug making updates to flows via API: https://issues.redhat.com/browse/KEYCLOAK-15545

**Comment by aba-rechsteiner** [comment]
FYI: we are already on Keycloak version 11.0.2 and the module works fine

**Comment by treydock** [comment]
Ya the issue is if you try to make updates to flows, you get the errors.  I have opened a patch against Keycloak to address this issue: https://github.com/keycloak/keycloak/pull/7441.  If you don't manage flows or don't make changes to flows, then 11.x works just fine with this module.

**Comment by treydock** [comment]
Closing in favor of #176

**Pull request closed without merging**
