### PR TITLE
Enable defining bind address for the Keycloak systemd service

### PR DESCRIPTION
**Pull request by mattock**
This is useful for example when there is a reverse proxy is in front of Keycloak

### CODE REVIEW

**Comment by treydock** [comment]
Need to update `.fixutres.yml` to use stdlib `4.25.0` and update `metadata.json` minimum version of stdlib to match.

**Comment by treydock** [comment]
Will need to rebase against master branch since #86 was merged.

**Comment by mattock** [comment]
Rebased and Travis seems happy now as well.

**Comment by treydock** [comment]
Released in v5.5.0

**Pull request merged**
